# Dockerfile
FROM mysql:8.4

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=zhb198691
ENV MYSQL_DATABASE=my1stdatabase
ENV MYSQL_USER=tina
ENV MYSQL_PASSWORD=zhb198691

# Expose MySQL port
EXPOSE 3306