name: 'tina_pipeline'
version: '1.0.0'

profile: 'tina_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  tina_pipeline:
    staging:
      +materialized: view
    marts:
      +materialized: incremental
      +unique_key: id
